name: RedMountainLife
favicon: null
layout_spectrum: 0.9879574254155159
typography_spectrum: 0.774470352800563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7826934903860092
  lightness: 0.011466220254078507
  saturation: 0.8274257415905595
  rhythmicContrast: 0.44156968779861927
purpose: []
